"""adiciona tabela lembretes

Revision ID: c4b9cce778a0
Revises: c9ac3c47c0ad
Create Date: 2026-04-13 17:15:16.269287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c4b9cce778a0'
down_revision: Union[str, None] = 'c9ac3c47c0ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lembretes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('dat_lembrete', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id_job', sa.String(length=100), nullable=True),
    sa.Column('sts_lembrete', sa.String(length=20), nullable=False),
    sa.Column('flg_ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lembretes_dat_lembrete'), 'lembretes', ['dat_lembrete'], unique=False)
    op.create_index(op.f('ix_lembretes_id_usuario'), 'lembretes', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_lembretes_sts_lembrete'), 'lembretes', ['sts_lembrete'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lembretes_sts_lembrete'), table_name='lembretes')
    op.drop_index(op.f('ix_lembretes_id_usuario'), table_name='lembretes')
    op.drop_index(op.f('ix_lembretes_dat_lembrete'), table_name='lembretes')
    op.drop_table('lembretes')
    # ### end Alembic commands ###
