"""cria tabelas iniciais

Revision ID: c9ac3c47c0ad
Revises: 
Create Date: 2026-04-12 22:56:10.378647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'c9ac3c47c0ad'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Habilitar extensao pgvector (obrigatorio antes das tabelas com Vector)
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cod_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('flg_ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_usuario')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('configuracoes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('modelo_preferido', sa.String(length=50), nullable=False),
    sa.Column('tema', sa.String(length=20), nullable=False),
    sa.Column('voz_resposta', sa.String(length=100), nullable=True),
    sa.Column('flg_briefing_diario', sa.Boolean(), nullable=False),
    sa.Column('horario_briefing', sa.Time(), nullable=False),
    sa.Column('flg_notificacoes', sa.Boolean(), nullable=False),
    sa.Column('preferencias', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracoes_id_usuario'), 'configuracoes', ['id_usuario'], unique=True)
    op.create_table('conversas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('flg_ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversas_id_usuario'), 'conversas', ['id_usuario'], unique=False)
    op.create_table('memorias',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('id_mem0', sa.String(length=100), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('metadados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flg_ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_mem0')
    )
    op.create_index(op.f('ix_memorias_categoria'), 'memorias', ['categoria'], unique=False)
    op.create_index(op.f('ix_memorias_id_usuario'), 'memorias', ['id_usuario'], unique=False)
    # Indice HNSW para busca vetorial eficiente (cosine similarity)
    op.execute("CREATE INDEX ON memorias USING hnsw (embedding vector_cosine_ops)")
    op.create_table('pessoas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('cod_pessoa', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('relacao', sa.String(length=100), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('metadados', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('flg_ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_pessoa')
    )
    op.create_index(op.f('ix_pessoas_id_usuario'), 'pessoas', ['id_usuario'], unique=False)
    op.create_table('subscricoes_push',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('chave_p256dh', sa.Text(), nullable=False),
    sa.Column('chave_auth', sa.Text(), nullable=False),
    sa.Column('dispositivo', sa.String(length=100), nullable=True),
    sa.Column('flg_ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscricoes_push_id_usuario'), 'subscricoes_push', ['id_usuario'], unique=False)
    op.create_table('tarefas_agendadas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('cron_expressao', sa.String(length=100), nullable=True),
    sa.Column('parametros', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sts_tarefa', sa.String(length=20), nullable=False),
    sa.Column('dat_ultima_execucao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dat_proxima_execucao', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarefas_agendadas_id_usuario'), 'tarefas_agendadas', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_tarefas_agendadas_sts_tarefa'), 'tarefas_agendadas', ['sts_tarefa'], unique=False)
    op.create_table('mensagens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_conversa', sa.Uuid(), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('modelo_usado', sa.String(length=50), nullable=True),
    sa.Column('tokens_entrada', sa.Integer(), nullable=True),
    sa.Column('tokens_saida', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_conversa'], ['conversas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_criado_em'), 'mensagens', ['criado_em'], unique=False)
    op.create_index(op.f('ix_mensagens_id_conversa'), 'mensagens', ['id_conversa'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_id_conversa'), table_name='mensagens')
    op.drop_index(op.f('ix_mensagens_criado_em'), table_name='mensagens')
    op.drop_table('mensagens')
    op.drop_index(op.f('ix_tarefas_agendadas_sts_tarefa'), table_name='tarefas_agendadas')
    op.drop_index(op.f('ix_tarefas_agendadas_id_usuario'), table_name='tarefas_agendadas')
    op.drop_table('tarefas_agendadas')
    op.drop_index(op.f('ix_subscricoes_push_id_usuario'), table_name='subscricoes_push')
    op.drop_table('subscricoes_push')
    op.drop_index(op.f('ix_pessoas_id_usuario'), table_name='pessoas')
    op.drop_table('pessoas')
    op.drop_index(op.f('ix_memorias_id_usuario'), table_name='memorias')
    op.drop_index(op.f('ix_memorias_categoria'), table_name='memorias')
    op.drop_table('memorias')
    op.drop_index(op.f('ix_conversas_id_usuario'), table_name='conversas')
    op.drop_table('conversas')
    op.drop_index(op.f('ix_configuracoes_id_usuario'), table_name='configuracoes')
    op.drop_table('configuracoes')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
