"""adiciona tabelas checklist listas e tarefas

Revision ID: f22aa210c728
Revises: c4b9cce778a0
Create Date: 2026-04-13 20:55:38.370189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'f22aa210c728'
down_revision: Union[str, None] = 'c4b9cce778a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cor', sa.String(length=20), nullable=False),
    sa.Column('icone', sa.String(length=50), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('flg_ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listas_id_usuario'), 'listas', ['id_usuario'], unique=False)
    op.create_table('tarefas_checklist',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_usuario', sa.Uuid(), nullable=False),
    sa.Column('id_lista', sa.Uuid(), nullable=True),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('prioridade', sa.String(length=20), nullable=False),
    sa.Column('dat_vencimento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('flg_concluida', sa.Boolean(), nullable=False),
    sa.Column('dat_concluida', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('flg_ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_lista'], ['listas.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarefas_checklist_criado_em'), 'tarefas_checklist', ['criado_em'], unique=False)
    op.create_index(op.f('ix_tarefas_checklist_dat_vencimento'), 'tarefas_checklist', ['dat_vencimento'], unique=False)
    op.create_index(op.f('ix_tarefas_checklist_flg_concluida'), 'tarefas_checklist', ['flg_concluida'], unique=False)
    op.create_index(op.f('ix_tarefas_checklist_id_lista'), 'tarefas_checklist', ['id_lista'], unique=False)
    op.create_index(op.f('ix_tarefas_checklist_id_usuario'), 'tarefas_checklist', ['id_usuario'], unique=False)
    op.create_index(op.f('ix_tarefas_checklist_prioridade'), 'tarefas_checklist', ['prioridade'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarefas_checklist_prioridade'), table_name='tarefas_checklist')
    op.drop_index(op.f('ix_tarefas_checklist_id_usuario'), table_name='tarefas_checklist')
    op.drop_index(op.f('ix_tarefas_checklist_id_lista'), table_name='tarefas_checklist')
    op.drop_index(op.f('ix_tarefas_checklist_flg_concluida'), table_name='tarefas_checklist')
    op.drop_index(op.f('ix_tarefas_checklist_dat_vencimento'), table_name='tarefas_checklist')
    op.drop_index(op.f('ix_tarefas_checklist_criado_em'), table_name='tarefas_checklist')
    op.drop_table('tarefas_checklist')
    op.drop_index(op.f('ix_listas_id_usuario'), table_name='listas')
    op.drop_table('listas')
    # ### end Alembic commands ###
